---
title: "Analysisng what I listen to"
author: "Josh Faure"
date: "`r Sys.Date()`"
output:
  html_document: 
    code_folding: hide
    toc: yes
    number_sections: true
    toc_depth: 3
    toc_float: yes
    theme: paper
editor_options:
  chunk_output_type: console
---

```{r setup, include=FALSE}
library(knitr)
knitr::opts_chunk$set(fig.path = 'plots/', fig.width = 8, fig.height = 5,
                      echo = TRUE, warning = FALSE, message = FALSE, 
                      dpi = 180, scipen=999)

library(tidyverse)
library(lubridate)
library(spotifyr)
theme_set(theme_bw())
set.seed(73)
`%notin%` <- Negate(`%in%`)
source('personal_access_tokens.R')
```

## My top songs over the years
```{r}
my_id <- '1256149806'
my_playlists <- get_user_playlists(my_id, limit = 50)
my_playlists2 <- get_user_playlists(my_id, offset = 50, limit = 50)
top_songs_playlists <- my_playlists %>% bind_rows(my_playlists2) %>% 
  filter(str_detect(name, "Your Top Songs")) %>% select(id, name) %>% 
  rename(playlist_id = id,
         playlist_name = name)

top_songs_playlists <- top_songs_playlists %>% dplyr::mutate(
  tracks = map(.x = playlist_id, .f = ~ get_playlist_tracks(., limit = 100))
) %>% unnest(cols = "tracks") %>% 
  transmute(
    playlist_id,
    playlist = playlist_name,
    track = `track.name`,
    track_id = `track.id`,
    artist = artist.name = map_chr(track.album.artists, function(x) x$name[1])
  )

tracks <- get_playlist_tracks(top_songs_playlists$playlist_id[1])$track.name
features <- get_track_audio_features(tracks$track.id)



# features <- get_track_audio_features(tracks$track.id)
# tracks2 <- tracks %>%
#   left_join(features, by=c('track.id' = 'id'))
# tolerance = 0.05
# tracks2 %>%
#   filter((energy>mean(energy)-tolerance)&(energy<mean(energy)+tolerance)&
#            (valence>mean(valence)-tolerance)&(valence<mean(valence)+tolerance)&
#          (track.popularity/100>mean(track.popularity/100)-tolerance)&(track.popularity/100<mean(track.popularity/100)+tolerance)) %>%
#   mutate(artist.name = map_chr(track.album.artists, function(x) x$name[1])) %>% 
#   select(artist.name,track.name,energy,valence,track.popularity) %>%
#   bind_rows(data.frame(artist.name = '---average---',track.name = '---average---',energy=mean(tracks2$energy),valence=mean(tracks2$valence),track.popularity=mean(tracks2$track.popularity))) %>%
#   arrange(energy) 
```

